### ISSUE TITLE
Rest service invocation - intermittent java.lang.NullPointerException at org.apache.catalina.connector.CoyoteAdapter.service

### ISSUE THREAD

**Issue by hemal0105** [javaee/glassfish#21839] opened 2017-06-14 05:00 UTC
Environment Details
GlassFish Version: Glassfish 4.1
JDK version: 1.7
OS: recurs on windows and linux both

----------

Problem Description:
While invoking rest service, intermittently, we are getting below mentioned error. After restart it gets resolved until some time(a couple of days) and again recurs. 

Since the error is intermittent and it might not be possible to reproduce but details are as follows,
Rest services are created using NetBeans IDE 8.0.2, "New RESTful Web Services from Patterns" features and deployed on Glassfish 4.1. While accessing the rest service, this error occurs and it does not able to reach till rest service.(No code in rest service is executed).
For rest service, no additional libraries are used apart from which are bundled in glassfish 4.1 and included in project by the "New RESTful Web Services from Patterns" wizard.

stack traces:

[2017-06-13T16:21:16.474+0530] [glassfish 4.1] [WARNING] [NCLS-CORE-00090] [9] [tid: _ThreadID=25 _ThreadName=http-listener-1(1)] [timeMillis: 1497351076474] [levelValue: 900] [[
  Internal Server error: MyApplication/webresources/myservice/getAllTypes
java.lang.NullPointerException
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:272)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:745)
]]

After researching about "NCLS-CORE-00090" identifier provided in the stack trace, found [THIS](http://markmail.org/thread/nhv3py72acxav72d#query:+page:1+mid:buuoykr6fihu2pfk+state:results
) link which states that issue is with grizzly framework and provides patch jar files for the same. However this patch jar files download links are expired so unable to test it.

Due to this issue we are unable to move our application to higher environment for production.

[//]: # "Please choose one each Type, Component, and Priority label"

**Comment by yaminikb** [comment] 2017-06-14 06:12
@hemal0105 Can you please try on GlassFish 5.0?

**Comment by hemal0105** [comment] 2017-06-14 06:35
It wont be possible for me to try on GlassFish 5.0 due to other dependencies.
However migrating to GlassFish 4.1.2 have any possibility to resolve the issue?

**Comment by sumauppa** [comment] 2017-06-30 11:58
@hemal0105 Could you please send us the exact steps to reproduce the issue. We could not reproduce this one as there are no clear instructions mentioned.

**Comment by rlubke** [comment] 2017-07-10 22:58
See https://github.com/javaee/glassfish/issues/21118.

This was fixed in Grizzly 2.3.17 according to issue, so this should be resolved in 5.0.  The team sustaining 4.1.x will need to integrate a later version.  

This should be closed as a duplicate and further comments be made on 21118.

**Closed by rlubke** 2017-07-10 22:58 UTC
Labels: Component: grizzly-kernel, Component: rest-interface, duplicate, Priority: Major, Type: Bug
