### ISSUE TITLE
Number of Stateful session beans in Passive state is not updated (always 0) in Jconsole

### ISSUE THREAD

**Issue by tak-9** [javaee/glassfish#21738] opened 2017-05-05 05:03 UTC
<b>Issue:</b>
The number of Stateful session beans in Passive state (passivecount) is not updated at all in Jconsole. The value in Jconsole is always 0 even if session beans are passivated.
Make sure GLASSFISH-21272 has been fixed before reproducing this bug.

<b>Steps to Reproduce Issue:</b>
1. Set Monitoring Level for Ejb Container as HIGH.
2. Restart Glassfish.
3. Deploy test application and access the test application.
http://localhost:8080/StatefulBeansTest/MyServlet?count=600
=> Displays a "Hello" message in server.log, then starts passivating EJBs with a message for each.
4. Check value in Jconsole.
service:jmx:rmi://localhost:8686/jndi/rmi://localhost:8686/jmxrmi

amx > stateful-session-bean-mon > /mon/server-mon [server] > StatefulBeansEAR/StatefulBeansTest.war/PassivationBean > StatefulBeansEAR/StatefulEJB.jar/PassivationBean > Attributes

=> Click to expand the "passivecount" cell in the table
=> Bug: Should show non-zero highWaterMark (ie max) count but the current/low/high are all 0. When this bug is fixed, the current and highWaterMark become non-zero.
Test application:

I have used the test application from this website (EJB passivation and activation example).
https://www.javacodegeeks.com/2013/08/ejb-passivation-and-activation-example.html
I will attach the ear I built for your convenience.

**Comment by tak-9** [comment] 2017-05-05 05:03
Download test application from here.

https://www.dropbox.com/s/axtxas4ol8j5tpm/StatefulBeansEAR.ear?dl=0

**Comment by tak-9** [comment] 2017-05-05 05:07
<b>Suggested Fix: </b>

```

diff --git "a/C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\TortoiseGit\\StatefulSessionContainer-508e6f0.001.java" "b/C:\\gf5\\glassfish\\main\\appserver\\ejb\\ejb-container\\src\\main\\java\\com\\sun\\ejb\\containers\\StatefulSessionContainer.java"
index dbf17ed661..a933ae0cc0 100644
--- "a/C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\TortoiseGit\\StatefulSessionContainer-508e6f0.001.java"
+++ "b/C:\\gf5\\glassfish\\main\\appserver\\ejb\\ejb-container\\src\\main\\java\\com\\sun\\ejb\\containers\\StatefulSessionContainer.java"
@@ -552,7 +552,14 @@ public final class StatefulSessionContainer
 
     protected EjbMonitoringStatsProvider getMonitoringStatsProvider(
             String appName, String modName, String ejbName) {
-        return new StatefulSessionBeanStatsProvider(this, getContainerId(), appName, modName, ejbName);
+        StatefulSessionBeanStatsProvider statsProvider = new StatefulSessionBeanStatsProvider(
+                this, getContainerId(), appName, modName, ejbName);
+        try {
+            statsProvider.setPassiveCount(backingStore.size());
+        } catch (BackingStoreException e) {
+            _logger.log(Level.WARNING, "Exception in backingStore.size()", e);
+        }
+        return statsProvider;
     }
 
```


```
 
 diff --git "a/C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\TortoiseGit\\StatefulSessionBeanStatsProvider-508e6f0.000.java" "b/C:\\gf5\\glassfish\\main\\appserver\\ejb\\ejb-container\\src\\main\\java\\com\\sun\\ejb\\monitoring\\stats\\StatefulSessionBeanStatsProvider.java"
index 6c02143091..d9224efc51 100644
--- "a/C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\TortoiseGit\\StatefulSessionBeanStatsProvider-508e6f0.000.java"
+++ "b/C:\\gf5\\glassfish\\main\\appserver\\ejb\\ejb-container\\src\\main\\java\\com\\sun\\ejb\\monitoring\\stats\\StatefulSessionBeanStatsProvider.java"
@@ -42,6 +42,8 @@ package com.sun.ejb.monitoring.stats;
 
 import com.sun.ejb.containers.StatefulSessionContainer;
 
+import java.util.concurrent.atomic.AtomicLong;
+
 import org.glassfish.external.probe.provider.annotations.*;
 import org.glassfish.external.statistics.*;
 import org.glassfish.external.statistics.impl.*;
@@ -59,14 +61,13 @@ public class StatefulSessionBeanStatsProvider extends EjbMonitoringStatsProvider
     private BoundedRangeStatisticImpl methodReadyStat = null;
     private BoundedRangeStatisticImpl passiveCount = null;
 
-    private int methodReadyCount = 0;
-    private StatefulSessionContainer delegate;
+    private AtomicLong methodReadyCount = new AtomicLong();
+    private AtomicLong passivations = new AtomicLong(); 
 
     public StatefulSessionBeanStatsProvider(StatefulSessionContainer delegate,
             long beanId, String appName, String moduleName, String beanName) {
 
         super(beanId, appName, moduleName, beanName);
-        this.delegate = delegate;
 
         long now = System.currentTimeMillis();
 
@@ -84,14 +85,14 @@ public class StatefulSessionBeanStatsProvider extends EjbMonitoringStatsProvider
     @ManagedAttribute(id="methodreadycount")
     @Description( "Number of stateful session beans in MethodReady state")
     public RangeStatistic getMethodReadyCount() {
-        methodReadyStat.setCurrent(methodReadyCount);
+        methodReadyStat.setCurrent(methodReadyCount.get());
         return methodReadyStat;
     }
 
     @ManagedAttribute(id="passivecount")
     @Description( "Number of stateful session beans in Passive state")
     public RangeStatistic getPassiveCount() {
-        passiveCount.setCurrent(delegate.getPassiveCount());
+        passiveCount.setCurrent(passivations.get());
         return passiveCount;
     }
 
@@ -103,7 +104,7 @@ public class StatefulSessionBeanStatsProvider extends EjbMonitoringStatsProvider
             @ProbeParam("ejbName") String ejbName) {
         if (this.beanId == beanId) {
             log ("methodReadyAddEvent", "StatefulSessionBeanStatsProvider");
-            methodReadyCount++;
+            methodReadyCount.incrementAndGet();
         }
     }
 
@@ -115,8 +116,38 @@ public class StatefulSessionBeanStatsProvider extends EjbMonitoringStatsProvider
             @ProbeParam("ejbName") String ejbName) {
         if (this.beanId == beanId) {
             log ("methodReadyRemoveEvent", "StatefulSessionBeanStatsProvider");
-            methodReadyCount--;
+            methodReadyCount.decrementAndGet();
+        }
+    }
+
+    @ProbeListener("glassfish:ejb:cache:beanPassivatedEvent")
+    public void ejbBeanPassivatedEvent(
+            @ProbeParam("beanId") long beanId,
+            @ProbeParam("appName") String appName,
+            @ProbeParam("modName") String modName,
+            @ProbeParam("ejbName") String ejbName,
+            @ProbeParam("success") boolean success) {
+        if (this.beanId == beanId && success) {
+            log ("beanPassivatedEvent", "StatefulSessionBeanStatsProvider");
+            passivations.incrementAndGet();
+        }
+    }
+
+    @ProbeListener("glassfish:ejb:cache:expiredSessionsRemovedEvent")
+    public void ejbExpiredSessionsRemovedEvent(
+            @ProbeParam("beanId") long beanId,
+            @ProbeParam("appName") String appName,
+            @ProbeParam("modName") String modName,
+            @ProbeParam("ejbName") String ejbName,
+            @ProbeParam("num") long num) {
+        if (this.beanId == beanId) {
+            log ("expiredSessionsRemovedEvent", "StatefulSessionBeanStatsProvider");
+            passivations.addAndGet(-num);
         }
     }
 
+    public void setPassiveCount(long passiveCount) {
+        passivations.set(passiveCount);
+    }
+
 }

```

**Comment by srinivaskrishnan** [comment] 2017-05-09 07:56
I am able to reproduce. Applied the patch. Found the following observation after applying the patch,

amx > stateful-session-bean-mon > /mon/server-mon [server] > StatefulBeansEAR/StatefulEJB.jar/PassivationBean > Attributes > passivecount -> current and highwatermark is 1200.
but
amx > stateful-session-bean-mon > /mon/server-mon [server] > StatefulBeansEAR/StatefulEJB.war/PassivationBean > Attributes > passivecount -> current and highwatermark is still zero.

Does StatefulBeansEAR/StatefulEJB.war/PassivationBean > Attributes > passivecount should also change or zero is fine. Or am I missed out some fix while applying the patch.

**Comment by tak-9** [comment] 2017-05-10 04:21
My understanding is that EJBs are passivated but the Servlet is not.  600 EJBs are created but the number of servlet is 1. So, I think what you are seeing is correct but please check it with another Glassfish developer if you can.

**Comment by yaminikb** [comment] 2017-06-29 16:05
Closing since fix is merged

**Closed by yaminikb** 2017-06-29 16:05 UTC
Labels: Component: monitoring, Priority: Major, Type: Bug

**Comment by srinivaskrishnan** [comment] 2017-07-21 08:36
Closing this as the other bug is fixed in the latest build.

**Comment by srinivaskrishnan** [comment] 2017-07-21 08:37
Closing this as the this bug referred in #22024 is fixed in the latest build.
