### ISSUE TITLE
Commons fileupload and tomcat derived issue still exists in glassfish

### ISSUE THREAD

**Issue by tsyamamoto** [javaee/glassfish#21992] opened 2017-07-06 00:59 UTC
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* GlassFish Version (and build number):5.0, 4.2, 3.1.2.2
* JDK version: all
* OS: all
* Database:

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

Commons fileupload and tomcat fixed file upload problem before.
http://svn.apache.org/viewvc?view=revision&revision=1743722
http://svn.apache.org/viewvc?view=revision&revision=1745058

The same code exists in the latest glassfish, and the same problem can be reproducible by using servlet fileupload web application.

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"
[//]: # "Please choose one each Type, Component, and Priority label"

**Comment by yaminikb** [comment] 2017-07-06 08:00
The problem has been addressed recently, hence closing this as duplicate of #21897

**Comment by tsyamamoto** [comment] 2017-07-06 08:07
In 21897, is the following code fixed?

appserver\web\web-core\src\main\java\org\apache\catalina\fileupload\MultipartStream.java

**Comment by yaminikb** [comment] 2017-07-06 13:54
Yes, it is.

**Comment by tsyamamoto** [comment] 2017-07-07 00:35
Unfortunately, the latest source code in git is wrong.
```java
        this.input = input; 
        this.bufSize = bufSize;
        this.buffer = new byte[bufSize];
        this.notifier = pNotifier;
```

It should be as follows.
```java
        this.input = input;
        this.bufSize = Math.max(bufSize, boundaryLength * 2);
        this.buffer = new byte[this.bufSize];
        this.notifier = pNotifier;
```

Please check tomcat and commons fileupload source code.

**Comment by tsyamamoto** [comment] 2017-07-14 06:09
Hi, how about my comment?

**Comment by yaminikb** [comment] 2017-07-15 13:58
@tsyamamoto Good catch! We will fix it.

**Closed** 2017-07-20 04:22 UTC
Labels: 5-0-triaged, Component: web_container, Priority: Major, Type: Bug
